name: CI/CD Whisper

on: [push]

jobs:
  build_run_whisper:
    name: Build/Run whisper
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Use bazel
        run: python3 bazelisk/bazelisk.py --version
      - name: Build binaries
        run: python bazelisk/bazelisk.py build --compilation_mode=opt --copt=-march=native :whisper
      - name: Run binaries
        run: bash deploy_whisper.sh && cd deployment && ./whisper -m ggml-tiny.en.bin -f samples_jfk.wav